### ISSUE TITLE
npm isn't up to date with the latest github version

### ISSUE THREAD

**Issue by stephenwil** [orangenpresse/grunt-phantomjs-screenshot#5]
Hi,
 When npm installing the module, the latest amendments with the 'server' option aren't coming down.
So tasks/phantomjs_screenshot.js & bin/ScreenShooter.js are behind.

Do you need to republish to npm?

Thanks

Stephen

**Comment by orangenpresse** [comment]
Hi,

you are right, I forgot to release the new version.
new version is online now.

Thank you very much!

**Comment by stephenwil** [comment]
Hey, no problem - and thanks for doing that :-)
